import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import {
  emitCatalogSource,
  generateCatalog,
} from '../../scripts/sync-catalog.ts'

const YAML_PATH = join(
  new URL('.', import.meta.url).pathname,
  '../../src/_vendor/config.yml',
)

describe('generateCatalog: end-to-end against vendored YAML', () => {
  test('yields every upstream client plus codex', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const ids = result.entries.map((e) => e.id)
    // Sorted alphabetically per generator invariant.
    expect(ids).toEqual([
      'claude-code',
      'claude-desktop',
      'cline',
      'codex',
      'continue',
      'crush',
      'cursor',
      'gemini',
      'goose',
      'kiro',
      'lmstudio',
      'opencode',
      'sema4',
      'vscode',
      'zed',
    ])
  })

  test('claude-desktop has stdio-only supportedTransports and mcpServers parent key', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const cd = result.entries.find((e) => e.id === 'claude-desktop')
    expect(cd).toBeDefined()
    expect(cd?.supportedTransports).toEqual(['stdio'])
    expect(cd?.emitterConfig.parentKey).toBe('mcpServers')
    expect(cd?.emitterConfig.transportTagKey).toBeUndefined()
  })

  test('claude-code has project override with stdio-only and type-tag injection', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const cc = result.entries.find((e) => e.id === 'claude-code')
    expect(cc?.supportedTransports).toEqual(['stdio', 'sse', 'http'])
    expect(cc?.projectSupportedTransports).toEqual(['stdio'])
    expect(cc?.projectFile).toBe('.mcp.json')
    expect(cc?.projectEmitterConfig?.transportTagKey).toBe('type')
  })

  test('vscode injects the type=stdio tag', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const vs = result.entries.find((e) => e.id === 'vscode')
    expect(vs?.emitterConfig.transportTagKey).toBe('type')
    expect(vs?.emitterConfig.parentKey).toBe('servers')
  })

  test('sema4 uses transport (not type) as the tag key', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const s4 = result.entries.find((e) => e.id === 'sema4')
    expect(s4?.emitterConfig.transportTagKey).toBe('transport')
  })

  test('zed injects source=custom and enabled=true', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const z = result.entries.find((e) => e.id === 'zed')
    expect(z?.emitterConfig.injectFields).toEqual({
      source: 'custom',
      enabled: true,
    })
  })

  test('goose uses simpleName transform and yaml-goose emitter', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const g = result.entries.find((e) => e.id === 'goose')
    expect(g?.emitterId).toBe('yaml-goose')
    expect(g?.emitterConfig.keyTransform).toBe('simpleName')
    expect(g?.emitterConfig.fieldRenames?.command).toBe('cmd')
    // Docker's goose entry writes `envs: {}` as a literal (no passthrough of
    // $JSON.env), so envs is an inject, not a rename.
    expect(g?.emitterConfig.fieldRenames?.env).toBeUndefined()
    expect(g?.emitterConfig.injectFields?.envs).toEqual({})
  })

  test('continue.dev uses yaml-continue emitter', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const c = result.entries.find((e) => e.id === 'continue')
    expect(c?.emitterId).toBe('yaml-continue')
  })

  test('opencode uses json commandAsArray with type=local + enabled=true injects', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const o = result.entries.find((e) => e.id === 'opencode')
    expect(o?.emitterId).toBe('json')
    expect(o?.emitterConfig.commandAsArray).toBe(true)
    expect(o?.emitterConfig.injectFields).toEqual({
      type: 'local',
      enabled: true,
    })
  })

  test('codex is emitted from post-processing with stdio + http', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const result = generateCatalog(yaml)
    const cx = result.entries.find((e) => e.id === 'codex')
    expect(cx?.emitterId).toBe('toml-codex')
    expect(cx?.supportedTransports).toEqual(['stdio', 'http'])
  })
})

describe('emitCatalogSource: snapshot shape', () => {
  test('emitted TS starts with generated-header comment and imports AgentId', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const src = emitCatalogSource(generateCatalog(yaml))
    expect(src.startsWith('/**')).toBe(true)
    expect(src).toContain('Generated by scripts/sync-catalog.ts')
    expect(src).toContain(`import type { AgentId } from '../types.ts'`)
    expect(src).toContain('export const CATALOG_V004')
  })

  test('emitter is deterministic: same YAML in, same source out', () => {
    const yaml = readFileSync(YAML_PATH, 'utf8')
    const a = emitCatalogSource(generateCatalog(yaml))
    const b = emitCatalogSource(generateCatalog(yaml))
    expect(a).toBe(b)
  })
})
