// Vendored from vercel-labs/skills@1.5.22 src/types.ts. See THIRD_PARTY_NOTICES.md
// for upstream attribution. Trimmed to the subset agent-skills-manager actually uses.

export type AgentType =
  | 'aider-desk'
  | 'amp'
  | 'antigravity'
  | 'antigravity-cli'
  | 'astrbot'
  | 'autohand-code'
  | 'augment'
  | 'bob'
  | 'claude-code'
  | 'openclaw'
  | 'cline'
  | 'codearts-agent'
  | 'codebuddy'
  | 'codemaker'
  | 'codestudio'
  | 'codex'
  | 'command-code'
  | 'continue'
  | 'cortex'
  | 'crush'
  | 'cursor'
  | 'deepagents'
  | 'devin'
  | 'dexto'
  | 'droid'
  | 'eve'
  | 'firebender'
  | 'forgecode'
  | 'gemini-cli'
  | 'github-copilot'
  | 'goose'
  | 'grok'
  | 'hermes-agent'
  | 'inference-sh'
  | 'iflow-cli'
  | 'jazz'
  | 'junie'
  | 'kilo'
  | 'kimchi'
  | 'kimi-code-cli'
  | 'kiro-cli'
  | 'kode'
  | 'lingma'
  | 'loaf'
  | 'mcpjam'
  | 'minimax-code'
  | 'mistral-vibe'
  | 'moxby'
  | 'mux'
  | 'neovate'
  | 'opencode'
  | 'openhands'
  | 'ona'
  | 'pi'
  | 'qoder'
  | 'qoder-cn'
  | 'qwen-code'
  | 'replit'
  | 'reasonix'
  | 'roo'
  | 'rovodev'
  | 'tabnine-cli'
  | 'terramind'
  | 'tinycloud'
  | 'trae'
  | 'trae-cn'
  | 'warp'
  | 'windsurf'
  | 'zed'
  | 'zcode'
  | 'zencoder'
  | 'zenflow'
  | 'pochi'
  | 'promptscript'
  | 'adal'
  | 'universal'

export interface AgentConfig {
  name: string
  displayName: string
  skillsDir: string
  /** Global skills directory. Set to undefined if the agent doesn't support global installation. */
  globalSkillsDir: string | undefined
  detectInstalled: () => Promise<boolean>
  /** Whether to show this agent in the universal agents list. Defaults to true. */
  showInUniversalList?: boolean
  /** Whether to display this universal agent in the interactive locked section. Defaults to true. */
  showInUniversalPrompt?: boolean
}
